version: 1.0.0
branches:
  only:
  - master
  - /release*/
  - develop
image: Visual Studio 2019
build_script:
- ps: ./.ci/build.ps1
test_script:
- ps: ./.ci/test.ps1
artifacts:
- path: artifacts/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: FS7OJwqKtXgQLcreC0htCtc30/5f6Hy8oipDyDg0/a1e70pA0uQ+0HxNk+EVdHNi
  on:
    branch: /^master|release\/.+$/
